# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_level <- function(D, p) {
    .Call(`_HiGarrote_get_level`, D, p)
}

contr_scale <- function(x, level_num) {
    .Call(`_HiGarrote_contr_scale`, x, level_num)
}

D_contr <- function(D, p, mi, me_num, quali_id, quanti_eq_id) {
    .Call(`_HiGarrote_D_contr`, D, p, mi, me_num, quali_id, quanti_eq_id)
}

U_j_cpp <- function(uni_level, p, mi, quali_id, quanti_eq_id, quanti_ineq_id, quali_contr) {
    .Call(`_HiGarrote_U_j_cpp`, uni_level, p, mi, quali_id, quanti_eq_id, quanti_ineq_id, quali_contr)
}

h_dist_cpp <- function(x, m, two_level, quali) {
    .Call(`_HiGarrote_h_dist_cpp`, x, m, two_level, quali)
}

h_j_cpp <- function(p, uni_level, m_list, two_level_id, quali_id) {
    .Call(`_HiGarrote_h_j_cpp`, p, uni_level, m_list, two_level_id, quali_id)
}

Psi_mat_cpp <- function(h_list_mat, rho) {
    .Call(`_HiGarrote_Psi_mat_cpp`, h_list_mat, rho)
}

initialize_NLLH_instance <- function(h_list_mat, n, replicate, y, nugget, epsilon, interpolate) {
    invisible(.Call(`_HiGarrote_initialize_NLLH_instance`, h_list_mat, n, replicate, y, nugget, epsilon, interpolate))
}

nllh_cpp_R <- function(rho_lambda) {
    .Call(`_HiGarrote_nllh_cpp_R`, rho_lambda)
}

nllh_GP_R <- function(rho) {
    .Call(`_HiGarrote_nllh_GP_R`, rho)
}

rho_lambda_optim <- function(ini_point, h_list_mat, n, replicate, y, lambda_lb, lambda_ub, nugget = 1e-6, epsilon = 1e-3, interpolate = TRUE) {
    .Call(`_HiGarrote_rho_lambda_optim`, ini_point, h_list_mat, n, replicate, y, lambda_lb, lambda_ub, nugget, epsilon, interpolate)
}

rho_optim_GP <- function(ini_point, h_list_mat, n, replicate, y, nugget = 1e-6, epsilon = 1e-3, interpolate = TRUE) {
    .Call(`_HiGarrote_rho_optim_GP`, ini_point, h_list_mat, n, replicate, y, nugget, epsilon, interpolate)
}

initialize_BETA_instance <- function(h_j_list, p, rho_list, mi) {
    invisible(.Call(`_HiGarrote_initialize_BETA_instance`, h_j_list, p, rho_list, mi))
}

r_j_cpp_R <- function(U_j_list, me_num) {
    .Call(`_HiGarrote_r_j_cpp_R`, U_j_list, me_num)
}

beta_nng_cpp_R <- function(U, R, lambda, replicate, n, y, Amat, s2) {
    .Call(`_HiGarrote_beta_nng_cpp_R`, U, R, lambda, replicate, n, y, Amat, s2)
}

