name: R-hub Checks

on:
  push:
    branches:
      - master  # Specify your branch name here
  pull_request:
    branches:
      - '*'
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  rhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R-hub CLI
        run: Rscript -e 'install.packages("rhub")'

      - name: R-hub check
        run: |
          Rscript -e 'rhub::check(platforms = c("windows-x86_64-release", "macos-highsierra-release", "linux-x86_64-debian-gcc"))'